version: "3.8"
services:
  dev-db:
    image: postgres:17
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: recep
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest
    networks:
      - nestnetwork
networks:
  nestnetwork: