version: "3.8"
services:
  dev-db:
    image: postgres:17
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: nest
    networks:
      - nestnetwork
networks:
  nestnetwork: